import { useState } from 'react';
import { ArrowLeft, ArrowRight, Check, ClipboardCheck, Edit3, Plus, Sparkles, Users } from 'lucide-react';
import { Alert, Avatar, Badge, Field, FormActions, Modal, Table, dateLabel, money, titleCase } from './components';
import { api } from './api';

const profileKeys = ['full_name', 'district', 'cnic', 'phone', 'city', 'cluster_id', 'household_size', 'dependents', 'school_age_children', 'monthly_income', 'marital_status', 'employment_status', 'owns_home', 'education_level', 'has_disability', 'chronic_illness_flag', 'date_of_birth', 'is_orphan', 'prior_assistance_count', 'domain_attributes', 'staff_notes', 'consent_given'];
const numberKeys = ['household_size', 'dependents', 'school_age_children', 'monthly_income', 'prior_assistance_count'];
const boolKeys = ['owns_home', 'has_disability', 'chronic_illness_flag', 'is_orphan'];

export function ProfileForm({ profile, mutate, onClose, open, pending }) {
  const [step, setStep] = useState(0), [error, setError] = useState('');
  const [form, setForm] = useState(() => Object.fromEntries(profileKeys.map(key => [key, key === 'consent_given' ? profile?.consent_given || false : key === 'domain_attributes' ? profile?.domain_attributes || {} : profile?.[key] ?? ''])));
  const set = (key, value) => setForm(f => ({ ...f, [key]: value }));
  function input(key, label, { type = 'text', required = false, hint, min, max } = {}) { return <Field label={label} hint={hint} key={key}><input type={type} required={required} value={form[key]} onChange={e => set(key, e.target.value)} min={min} max={max} maxLength={type === 'text' ? 200 : undefined}/></Field>; }
  function select(key, label, options) { return <Field label={label} key={key}><select value={String(form[key])} onChange={e => set(key, e.target.value)}><option value="">Not recorded</option>{options.map(([v, text]) => <option key={v} value={v}>{text}</option>)}</select></Field>; }
  const enumSelect = (key, label, values) => select(key, label, values.map(v => [v, titleCase(v)]));
  async function submit(e) {
    e.preventDefault(); setError('');
    if (step < 2) { setStep(step + 1); return; }
    const body = { ...form };
    for (const key of profileKeys) if (body[key] === '') body[key] = null;
    for (const key of numberKeys) body[key] = body[key] === null ? null : Number(body[key]);
    for (const key of boolKeys) body[key] = body[key] === null ? null : String(body[key]) === 'true';
    try { const result = await mutate(profile ? `/profiles/${profile.id}` : '/profiles', body, profile ? 'Profile updated and discovery refreshed.' : 'Beneficiary registered. Discovery and duplicate checks completed.', profile ? 'PUT' : 'POST'); open({ type: 'profile', id: profile?.id || result.profile.id }); }
    catch (err) { setError(err.message); }
  }
  return <Modal wide title={profile ? 'Update beneficiary profile' : 'Register a beneficiary'} subtitle="Enter details in conversation. Optional information can be completed later." onClose={() => !pending && onClose()}><div className="form-steps">{['Personal details', 'Household & needs', 'Review & consent'].map((s, i) => <button type="button" key={s} disabled={i > step} className={i === step ? 'active' : i < step ? 'done' : ''} onClick={() => setStep(i)}><span>{i < step ? <Check size={13}/> : i + 1}</span>{s}</button>)}</div><form onSubmit={submit}>
    {error && <Alert type="error">{error}</Alert>}
    {step === 0 && <><h3 className="section-title">Let’s start with the person.</h3><div className="form-grid">{input('full_name', 'Full name *', { required: true })}{input('district', 'District *', { required: true })}{input('cnic', 'CNIC', { hint: '13 digits. Leave blank if not available.' })}{input('phone', 'Contact number', { type: 'tel' })}{input('city', 'City / locality')}{input('cluster_id', 'Operational cluster', { hint: 'Alkhidmat cluster, if known.' })}{input('date_of_birth', 'Date of birth', { type: 'date', max: new Date().toISOString().slice(0, 10) })}{enumSelect('marital_status', 'Marital status', ['single', 'married', 'widowed', 'divorced'])}</div></>}
    {step === 1 && <><h3 className="section-title">Understand the household.</h3><div className="form-grid three">{input('household_size', 'Household members', { type: 'number', min: 1, max: 100 })}{input('dependents', 'Dependents', { type: 'number', min: 0, max: 100 })}{input('school_age_children', 'School-age children', { type: 'number', min: 0, max: 100 })}{input('monthly_income', 'Monthly income (PKR)', { type: 'number', min: 0 })}{enumSelect('employment_status', 'Employment status', ['unemployed', 'daily_wage', 'self_employed', 'salaried'])}{input('prior_assistance_count', 'Previous assistance count', { type: 'number', min: 0, max: 1000 })}</div><h3 className="section-title">Education, health & circumstances</h3><div className="form-grid">{enumSelect('education_level', 'Education level', ['none', 'primary', 'matric', 'intermediate', 'graduate'])}{select('owns_home', 'Owns a home', [['true', 'Yes'], ['false', 'No']])}{select('has_disability', 'Disability reported', [['true', 'Yes'], ['false', 'No']])}{select('chronic_illness_flag', 'Chronic illness reported', [['true', 'Yes'], ['false', 'No']])}{select('is_orphan', 'Orphan status', [['true', 'Yes'], ['false', 'No']])}</div><Field label="Caseworker notes" hint="Human context only. Notes are not used for eligibility scoring."><textarea rows={3} value={form.staff_notes} onChange={e => set('staff_notes', e.target.value)} maxLength={5000}/></Field></>}
    {step === 2 && <><div className="profile-banner"><Avatar name={form.full_name}/><div><h3>{form.full_name}</h3><p>{form.district}{form.city && ` · ${form.city}`}</p></div><Badge status="pending_review">Ready to register</Badge></div><div className="review-facts">{[['Monthly income', form.monthly_income === '' ? 'Not recorded' : money(form.monthly_income)], ['Household size', form.household_size || 'Not recorded'], ['Dependents', form.dependents === '' ? 'Not recorded' : form.dependents], ['Contact', form.phone || 'Not recorded'], ['Employment', titleCase(form.employment_status)], ['Previous assistance', form.prior_assistance_count === '' ? 'Not recorded' : form.prior_assistance_count]].map(([k, v]) => <div key={k}><small>{k}</small><strong>{v}</strong></div>)}</div><Alert>Saving checks active program rules and flags potential duplicate records. Suggestions go to staff review; nobody is enrolled or contacted automatically.</Alert><label className="consent"><input type="checkbox" required checked={form.consent_given} onChange={e => set('consent_given', e.target.checked)}/><span>The beneficiary has agreed to these details being recorded and used by Alkhidmat staff to assess support needs.</span></label></>}
    <div className="form-actions"><button type="button" className="button secondary" disabled={pending} onClick={() => step > 0 ? setStep(step - 1) : onClose()}>{step > 0 ? <><ArrowLeft size={16}/> Back</> : 'Cancel'}</button><button className="button primary" type="submit" disabled={pending}>{pending ? 'Saving & checking…' : step === 2 ? profile ? 'Save profile changes' : 'Register & discover support' : 'Continue'}{!pending && <ArrowRight size={16}/>}</button></div>
  </form></Modal>;
}

export function ProfileDetail({ profile, data, open, onClose, mutate, pending }) {
  const [results, setResults] = useState(null), [error, setError] = useState('');
  if (!profile) return <Modal title="Profile unavailable" onClose={onClose}><p>This profile is no longer in your accessible workspace.</p></Modal>;
  const matches = data.matches.filter(r => r.beneficiary_id === profile.id);
  const applications = data.applications.filter(r => r.beneficiary_id === profile.id);
  async function discover() { try { setError(''); setResults(await mutate(`/profiles/${profile.id}/discover`, undefined, 'Discovery refreshed from the current profile and program rules.')); } catch (e) { setError(e.message); } }
  return <Modal wide title="Beneficiary case file" subtitle="A shared record of circumstances and support." onClose={onClose}><div className="profile-banner"><Avatar name={profile.full_name}/><div><h2>{profile.full_name}</h2><p>{profile.district} · Registered {dateLabel(profile.created_at)}</p></div><button className="button secondary small" onClick={() => open({ type: 'profile-form', profile })}><Edit3 size={15}/> Edit profile</button></div><div className="review-facts">{[['Monthly income', money(profile.monthly_income)], ['Household', `${profile.household_size ?? '—'} members`], ['Dependents', profile.dependents ?? '—'], ['Phone', profile.phone || 'Not recorded'], ['CNIC', profile.cnic || 'Not recorded'], ['School-age children', profile.school_age_children ?? '—'], ['Disability', profile.has_disability == null ? 'Not recorded' : profile.has_disability ? 'Yes' : 'No'], ['Chronic illness', profile.chronic_illness_flag == null ? 'Not recorded' : profile.chronic_illness_flag ? 'Yes' : 'No'], ['Previous assistance', profile.prior_assistance_count ?? '—']].map(([key, value]) => <div key={key}><small>{key}</small><strong>{value}</strong></div>)}</div>{profile.staff_notes && <div className="case-note"><strong>Caseworker note</strong><p>{profile.staff_notes}</p></div>}<div className="inline-heading"><h3>Program discovery</h3><button className="button small primary" disabled={pending} onClick={discover}><Sparkles size={15}/> Refresh discovery</button></div>{error && <Alert type="error">{error}</Alert>}<Table rows={results || matches} pageSize={5} empty="No program suggestions yet" columns={[
    { label: 'Program', render: r => r.program_name || data.programs.find(p => p.id === r.program_id)?.name }, { label: 'Status', render: r => <Badge status={r.status}/> }, { label: 'Explanation', render: r => <span className="reason-cell">{r.reason}</span> },
  ]}/><div className="inline-heading"><h3>Applications & support</h3><button className="button small secondary" onClick={() => open({ type: 'application', profileId: profile.id })}><Plus size={15}/> Direct application</button></div><Table rows={applications} empty="No applications recorded" columns={[
    { label: 'Program', render: a => data.programs.find(p => p.id === a.program_id)?.name }, { label: 'Status', render: a => <Badge status={a.status}/> }, { label: 'Requested', render: a => money(a.amount_requested) }, { label: 'Support recorded', render: a => money(a.amount_disbursed) },
  ]}/><div className="panel-note">Discovery scores estimate a possible fit. Human verification and approval are required before support is recorded.</div></Modal>;
}

export function ApplicationForm({ data, profileId, mutate, pending, onClose }) {
  const [error, setError] = useState('');
  async function submit(e) { e.preventDefault(); const body = Object.fromEntries(new FormData(e.currentTarget)); body.amount_requested = body.amount_requested ? Number(body.amount_requested) : null; try { await mutate('/applications', body, 'Direct application recorded. It now needs the same verification as every other case.'); onClose(); } catch (err) { setError(err.message); } }
  return <Modal title="Record a direct application" subtitle="Use this when the beneficiary has explicitly asked for this program." onClose={() => !pending && onClose()}><form onSubmit={submit}>{error && <Alert type="error">{error}</Alert>}<Field label="Beneficiary"><select name="beneficiary_id" required defaultValue={profileId || ''}><option value="" disabled>Select a beneficiary</option>{data.profiles.map(p => <option key={p.id} value={p.id}>{p.full_name} · {p.district}</option>)}</select></Field><Field label="Requested program"><select name="program_id" required defaultValue=""><option value="" disabled>Select a program</option>{data.programs.filter(p => p.active).map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Field label="Amount requested (PKR)" hint="Leave blank for in-kind support."><input name="amount_requested" type="number" min="1"/></Field><Alert>A direct application does not bypass verification or receive a ranking advantage.</Alert><FormActions busy={pending} onCancel={onClose} label="Record application"/></form></Modal>;
}

export function VerificationForm({ data, record, mutate, pending, onClose }) {
  const profile = data.profiles.find(p => p.id === record.beneficiary_id), program = data.programs.find(p => p.id === record.program_id);
  const [outcome, setOutcome] = useState('verified'), [need, setNeed] = useState(''), [elsewhere, setElsewhere] = useState(''), [error, setError] = useState('');
  async function submit(e) {
    e.preventDefault(); setError(''); const values = Object.fromEntries(new FormData(e.currentTarget));
    const body = { beneficiary_id: profile.id, program_id: program.id, outcome, need_confirmed: need === 'true', assistance_elsewhere: elsewhere === 'true',
      urgency_level: values.urgency_level, notes: values.notes, verified_income: values.verified_income === '' ? null : Number(values.verified_income), verified_household_size: values.verified_household_size === '' ? null : Number(values.verified_household_size), amount_requested: values.amount_requested === '' ? null : Number(values.amount_requested) };
    try { await mutate('/verifications', body, outcome === 'verified' ? 'Assessment saved. The verified candidate has joined the unified pool.' : 'Assessment saved and the case closed for this program.'); onClose(); } catch (err) { setError(err.message); }
  }
  return <Modal wide title="Record a needs assessment" subtitle={`${profile.full_name} · ${program.name}`} onClose={() => !pending && onClose()}><form onSubmit={submit}>{error && <Alert type="error">{error}</Alert>}<div className="profile-banner"><Avatar name={profile.full_name}/><div><h3>{profile.full_name}</h3><p>{profile.district} · {profile.phone || 'No contact number recorded'}</p></div><Badge status={record.entry_path || 'ai_identified'}/></div><Alert>Confirm these facts during assessment. Current profile values are shown for reference; saving records a dated verification snapshot.</Alert><div className="form-grid"><Field label="Actual need confirmed? *"><select required value={need} onChange={e => setNeed(e.target.value)}><option value="">Select an answer</option><option value="true">Yes, need confirmed</option><option value="false">No</option></select></Field><Field label="Similar assistance received elsewhere? *"><select required value={elsewhere} onChange={e => setElsewhere(e.target.value)}><option value="">Select an answer</option><option value="false">No</option><option value="true">Yes</option></select></Field><Field label="Verified monthly income (PKR)"><input type="number" name="verified_income" min="0" defaultValue={profile.monthly_income ?? ''} required={outcome === 'verified'}/></Field><Field label="Verified household size"><input type="number" name="verified_household_size" min="1" max="100" defaultValue={profile.household_size ?? ''} required={outcome === 'verified'}/></Field><Field label="Urgency"><select name="urgency_level" defaultValue="medium">{['low', 'medium', 'high', 'critical'].map(v => <option key={v} value={v}>{titleCase(v)}</option>)}</select></Field><Field label="Amount requested (PKR)"><input name="amount_requested" type="number" min="1" defaultValue={record.amount_requested ?? ''}/></Field></div><h3 className="section-title">Record the outcome</h3><Field label="Assessment outcome"><select value={outcome} onChange={e => setOutcome(e.target.value)}>{[['verified', 'Verified — join candidate pool'], ['no_actual_need', 'No actual need'], ['assisted_elsewhere', 'Already assisted elsewhere'], ['not_eligible', 'Not eligible'], ['unreachable', 'Could not reach'], ['declined', 'Beneficiary declined']].map(([v, text]) => <option key={v} value={v}>{text}</option>)}</select></Field><Field label="Assessment notes *" hint="Document what was checked and the basis for the outcome."><textarea name="notes" rows={3} minLength={3} maxLength={5000} required/></Field><FormActions busy={pending} onCancel={onClose} label="Save assessment"/></form></Modal>;
}
